package org.umoja4life.drilltutor

import android.util.Log

/**
 * Environment
 * The Central Nervous System of the Application.
 * - Single Source of Truth for State and Configuration.
 * - Manages Logging.
 */
object Environment {

    // --- IDENTITY & VERSION ---
    const val APP_NAME = "DrillTutor"

    // We map these from the BuildConfig generated by your Gradle script
    val VERSION_NAME: String = BuildConfig.VERSION_NAME
    val VERSION_CODE: String = BuildConfig.DRILLTUTOR_VERSION_CODE
    val IS_DEBUG: Boolean = BuildConfig.DEBUG

    // --- CONFIGURATION ---
    // Explicit default to English, ignoring system locale for now.
    // This will eventually be a persisted setting.
    var currentLanguage: String = "en"

    // --- LOGGING UTILITIES ---
    private const val LOG_TAG = APP_NAME

    fun logInfo(msg: String) {
        // Standard info log
        Log.i(LOG_TAG, msg)
    }

    fun logDebug(msg: String) {
        if (IS_DEBUG) {
            Log.d(LOG_TAG, "DEBUG: $msg")
        }
    }

    fun logWarn(msg: String) {
        Log.w(LOG_TAG, "WARN: $msg")
    }

    fun logError(msg: String) {
        Log.e(LOG_TAG, "ERROR: $msg")
    }

    // --- INITIALIZATION ---
    // Called once when the application starts (in DrillTutorApplication)
    fun init() {
        logInfo("Environment Initialized.")
        logInfo("Version: $VERSION_NAME (Build $VERSION_CODE)")
        logInfo("Language set to: $currentLanguage")
    }
}